#!/bin/bash

set -e
set -u

if [[ -n "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%TIPPECANOE_VERSION%%/$TIPPECANOE_VERSION/" \
            "Dockerfile-$VARIANT.template" >Dockerfile

        docker \
            build -t "quay.io/azavea/tippecanoe:${TIPPECANOE_VERSION%.*}-$VARIANT" .

        scripts/test

        docker images
    fi
fi
