name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.35.0"]
        variant: ["slim"]
    env:
      DOCKER_BUILDKIT: 1
      CI: 1
      TIPPECANOE_VERSION: ${{ matrix.version }}
      VARIANT: ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v2

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
